on:
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: A job to test html pages
    permissions:
      contents: write
      pages: write
    steps:  
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run simple script
        run: bash .github/script.sh
      - name: Validate HTML
        uses: wjdp/htmltest-action@master
        with:
          path: .
      - name: Deploy to GH Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
