on:
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: A job to test html pages
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Validate HTML
        uses: jonathan76/html5-validator@main
        with:
          html_files: '**/*.html'
      - name: Validate HTML links
        uses: modernweb-dev/check-html-links-action@v1
        with:
          html_files: '**/*.html'
  deploy:
    - name: Deploy to GH Pages
    if: github.event_name == 'push'
    steps:
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
